name: Build RT-AC1200G+ Firmware

on:
  workflow_dispatch:
    inputs:
      skip_download:
        description: 'Skip download & extraction'
        required: false
        default: 'false'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install dependencies
      run: |
        sudo dpkg --add-architecture i386
        sudo apt-get update
        sudo apt-get install -y \
          build-essential gcc g++ make cmake patch git unzip wget \
          libncurses5-dev m4 bison gawk flex zlib1g-dev autoconf autopoint \
          libtool shtool autogen mtd-utils intltool sharutils \
          docbook-xsl xsltproc u-boot-tools device-tree-compiler \
          python2 gperf liblzo2-dev uuid-dev lzma-dev liblzma-dev \
          binutils-dev dos2unix qemu \
          libglib2.0-dev gtk-doc-tools \
          libc6-i386 lib32stdc++6 lib32z1 libelf1:i386 libncurses5:i386
        sudo apt-get install -y --no-install-recommends autoconf automake bash bison bzip2 diffutils file flex g++ gawk gcc-multilib gettext gperf groff-base libncurses-dev libexpat1-dev libslang2 libssl-dev libtool libxml-parser-perl make patch perl pkg-config  sed shtool tar texinfo unzip zlib1g zlib1g-dev

        sudo apt-get install  -y lib32stdc++6 lib32z1-dev
        
        sudo apt-get  -y --no-install-recommends install automake1.11
        
        sudo apt-get  -y install libelf-dev:i386 libelf1:i386
        
        sudo apt-get  -y --no-install-recommends install lib32z1-dev lib32stdc++6

    - name: Cache asuswrt source & toolchain
      uses: actions/cache@v3
      with:
        path: asuswrt
        key: ${{ runner.os }}-asuswrt-${{ hashFiles('**/GPL_RT_AC1200GPlus_*.zip') }}

    - name: Download and extract ASUS GPL source
      if: ${{ github.event.inputs.skip_download != 'true' }}
      run: |
        wget https://dlcdnets.asus.com/pub/ASUS/wireless/RT-AC1200G+/GPL_RT_AC1200GPlus_300438252272.zip -O GPL_RT_AC1200GPlus.zip

        # 解压 zip 得到 tgz
        unzip GPL_RT_AC1200GPlus.zip

        # 解压 tgz
        tar -xzf GPL_RT-AC1200G+_3.0.0.4.382.52272-g73d3ea2_fix.tgz
    - name: Add toolchain to PATH
      run: echo "/home/runner/work/Build-AC1200G-Firmware/Build-AC1200G-Firmware/asuswrt/release/src-rt-9.x/src/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin" >> $GITHUB_PATH

    - name: Setup toolchain and build firmware
      run: |
        SRC_DIR=asuswrt/release/src-rt-9.x/src
        TOOLCHAIN_BIN=asuswrt/release/src-rt-9.x/src/toolchains/hndtools-arm-linux-2.6.36-uclibc-4.5.3/bin

        # 编译固件
        cd $SRC_DIR
        make RT-AC1200G+

    - name: Cache build output (optional)
      uses: actions/cache@v3
      with:
        path: asuswrt/release/src-rt-9.x/src/images
        key: ${{ runner.os }}-asuswrt-build-${{ github.sha }}

    - name: Upload firmware artifact
      uses: actions/upload-artifact@v4
      with:
        name: firmware
        path: asuswrt/release/src-rt-9.x/src/images/*.trx
